# Generated by Django 4.2.13 on 2024-07-14 18:29

import apps.events.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название ивента')),
                ('slug', models.SlugField(blank=True, help_text='Данное поле заполнять не нужно, оно заполняется автоматически', verbose_name='Слаг')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('preview', models.ImageField(blank=True, upload_to=apps.events.models.event_images_upload_to, verbose_name='Фото')),
                ('price', models.PositiveSmallIntegerField(verbose_name='Цена')),
                ('country', models.CharField(max_length=100, verbose_name='Страна ивента')),
                ('event_start', models.SmallIntegerField(verbose_name='Число начала ивента')),
                ('event_end', models.SmallIntegerField(verbose_name='Число конца ивента')),
                ('days', models.SmallIntegerField(verbose_name='Количество дней тура')),
                ('nights', models.SmallIntegerField(verbose_name='Количество ночей тура')),
                ('gathering_place', models.CharField(max_length=100, verbose_name='Место сбора группы')),
                ('minimum_age', models.IntegerField(verbose_name='Минимальный возраст')),
                ('people_in_group', models.IntegerField(verbose_name='Количество человек в группе')),
                ('event_type', models.CharField(choices=[(None, '-'), ('Мировой', 'World'), ('По узбекистану', 'Local')], default='Мировой', max_length=20, verbose_name='Тип тура')),
            ],
            options={
                'verbose_name': 'Ивент',
                'verbose_name_plural': 'Ивенты',
            },
        ),
        migrations.CreateModel(
            name='EventTourProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Слаг')),
                ('day', models.IntegerField(help_text='День тура, например: "1 день, 2 день"', verbose_name='День')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_program', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventTourProgramGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('event_tour_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_program_gallery', to='events.eventtourprogram')),
            ],
        ),
        migrations.CreateModel(
            name='EventPriceNotIncluded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Текст')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_not_included', to='events.event', verbose_name='Тур')),
            ],
        ),
        migrations.CreateModel(
            name='EventPriceIncluded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Текст')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_included', to='events.event', verbose_name='Тур')),
            ],
        ),
        migrations.CreateModel(
            name='EventGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.events.models.event_images_gallery_upload_to, verbose_name='Фото')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_gallery', to='events.event', verbose_name='Ивент')),
            ],
        ),
    ]
