# Generated by Django 4.2.13 on 2024-07-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtourprogram',
            name='slug',
        ),
    ]
