# Generated by Django 4.2.13 on 2024-07-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_eventtourprogram_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtourprogram',
            options={'verbose_name': 'Программа тура', 'verbose_name_plural': 'Программа тура'},
        ),
    ]
