# Generated by Django 4.2.13 on 2024-07-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventtourprogram_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventgallery',
            options={'verbose_name': 'Фото в галлерию', 'verbose_name_plural': 'Галлерея тура'},
        ),
        migrations.AlterModelOptions(
            name='eventpriceincluded',
            options={'verbose_name': 'Включено в цену', 'verbose_name_plural': 'Условия (Включено в цену)'},
        ),
        migrations.AlterModelOptions(
            name='eventpricenotincluded',
            options={'verbose_name': 'Не включено в цену', 'verbose_name_plural': 'Условия (Не включено в цену)'},
        ),
        migrations.AlterModelOptions(
            name='eventtourprogram',
            options={'verbose_name': 'День программы тура', 'verbose_name_plural': 'Дни программы тура'},
        ),
        migrations.AlterModelOptions(
            name='eventtourprogramgallery',
            options={'verbose_name': 'Фото дня программы тура', 'verbose_name_plural': 'Фото дней программы тура'},
        ),
        migrations.AddField(
            model_name='eventgallery',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
