# Generated by Django 4.2.13 on 2024-07-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_eventgallery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventgallery',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
