# Generated by Django 4.2.13 on 2024-07-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_eventgallery_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_end',
            field=models.DateField(verbose_name='Число конца ивента'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start',
            field=models.DateField(verbose_name='Число начала ивента'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[(None, '-'), ('world', 'Мировой'), ('uzbekistan', 'По узбекистану')], default='world', max_length=20, verbose_name='Тип тура'),
        ),
    ]
