# Generated by Django 4.2.13 on 2024-07-22 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_event_end_alter_event_event_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='country_from',
            field=models.CharField(default='Ташкент', max_length=100, verbose_name='Страна вылета'),
        ),
    ]
