# Generated by Django 4.2.13 on 2024-07-24 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_children_tourist'),
        ('events', '0008_alter_event_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people', models.PositiveSmallIntegerField(verbose_name='Кол-во отдыхающих')),
                ('number_of_children', models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во детей')),
                ('children', models.ManyToManyField(related_name='tour_children', to='users.children')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_booking', to='events.event')),
                ('tourists', models.ManyToManyField(related_name='tour_tourists', to='users.tourist')),
            ],
            options={
                'verbose_name': 'Бронь тура',
                'verbose_name_plural': 'Брони тура',
            },
        ),
    ]
