# Generated by Django 4.2.13 on 2024-07-24 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_tourbooking_children_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourbooking',
            name='children',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='tourists',
        ),
    ]
