# Generated by Django 4.2.13 on 2024-07-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_tourist_tour_booking'),
        ('events', '0011_remove_tourbooking_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbooking',
            name='tourists',
            field=models.ManyToManyField(blank=True, null=True, related_name='tour_booking', to='users.tourist'),
        ),
    ]
