# Generated by Django 4.2.13 on 2024-07-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_tourbooking_tourists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourbooking',
            name='number_of_people',
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='number_of_adult',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во отдыхающих'),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='number_of_babies',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Кол-во младенцев'),
        ),
    ]
