# Generated by Django 4.2.13 on 2024-08-03 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_remove_tourbooking_tourists_tourbooking_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TourBooking',
        ),
    ]
