# Generated by Django 4.2.13 on 2024-08-05 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0015_delete_tourbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_adult', models.SmallIntegerField(verbose_name='Кол-во отдыхающих')),
                ('total_children', models.SmallIntegerField(verbose_name='Кол-во детей')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_booking', to='events.event', verbose_name='Тур')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_booking', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронь тура',
                'verbose_name_plural': 'Брони туров',
            },
        ),
    ]
