# Generated by Django 4.2.13 on 2024-08-13 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_event_country_en_event_country_from_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventbooking',
            name='event_type',
            field=models.CharField(blank=True, choices=[(None, '-'), ('world', 'Мировой'), ('uzbekistan', 'По узбекистану')], default='world', max_length=20, null=True, verbose_name='Тип тура'),
        ),
    ]
