# Generated by Django 4.2.13 on 2024-08-20 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0018_eventbooking_event_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tours', models.ManyToManyField(related_name='favorites', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранный тур',
                'verbose_name_plural': 'Избранные туры',
            },
        ),
    ]
