# Generated by Django 4.2.13 on 2024-08-20 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0019_favoritetour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoritetour',
            name='tours',
        ),
        migrations.AlterField(
            model_name='favoritetour',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='favoritetour',
            name='tours',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='events.event', verbose_name='Тур'),
        ),
    ]
