# Generated by Django 4.2.13 on 2024-08-20 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_remove_favoritetour_tours_alter_favoritetour_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FavoriteTour',
        ),
    ]
