# Generated by Django 4.2.13 on 2024-08-26 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_delete_favoritetour'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventBooking',
        ),
    ]
