# Generated by Django 4.2.13 on 2024-09-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_delete_eventbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rating',
            field=models.CharField(choices=[('four_five', '4.5+'), ('four', '4+'), ('three', '3+')], default='four_five', max_length=15, verbose_name='Рейтинг'),
        ),
    ]
