# Generated by Django 4.2.13 on 2025-01-13 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_event_corporate_client_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImportantOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Текст')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='important_moments', to='events.event', verbose_name='Тур')),
            ],
            options={
                'verbose_name': 'Важные моменты',
                'verbose_name_plural': 'Важные моменты',
            },
        ),
    ]
