# Generated by Django 4.2.13 on 2025-01-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_eventimportantoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimportantoption',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='eventimportantoption',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='eventimportantoption',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Текст'),
        ),
    ]
