# Generated by Django 4.2.13 on 2025-01-17 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0024_remove_hotel_event'),
        ('events', '0027_eventimportantoption_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.hotel', verbose_name='Отель проживания'),
        ),
    ]
