# Generated by Django 4.2.13 on 2025-02-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_event_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='hotel',
        ),
        migrations.AddField(
            model_name='event',
            name='hotel_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отель проживания'),
        ),
    ]
