# Generated by Django 4.2.13 on 2024-08-26 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0022_delete_eventbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, choices=[(None, '-'), ('world', 'Мировой'),
                                                                     ('uzbekistan', 'По узбекистану')], default='world',
                                                max_length=20, null=True, verbose_name='Тип тура')),
                ('total_adult', models.SmallIntegerField(verbose_name='Кол-во отдыхающих')),
                ('total_children', models.SmallIntegerField(verbose_name='Кол-во детей')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_booking',
                                            to='events.event', verbose_name='Тур')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_booking',
                                           to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Бронь тура',
                'verbose_name_plural': 'Брони туров',
            },
        ),
    ]
