# Generated by Django 4.2.13 on 2024-08-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='beach_line',
            field=models.CharField(choices=[('first', 'Первая'), ('second', 'Вторая'), ('third', 'Третья')], default='first', max_length=50, verbose_name='Линия пляжа'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='beach_type',
            field=models.CharField(choices=[('sand', 'Песок'), ('pebble', 'Галька'), ('platform', 'Платформа')], default='sand', max_length=50, verbose_name='Тип пляжа'),
        ),
    ]
