# Generated by Django 4.2.13 on 2024-08-08 04:42

import apps.hotels.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_beach_line_hotel_beach_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название номера')),
                ('is_all_inclusive', models.BooleanField(default=True, verbose_name='Все включено?')),
                ('description', models.TextField(verbose_name='Удобства в номере')),
                ('nights', models.IntegerField(verbose_name='Кол-во ночей')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('until', models.DateField(verbose_name='До')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='hotels.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Номер в отеле',
                'verbose_name_plural': 'Номера в отеле',
            },
        ),
        migrations.CreateModel(
            name='HotelRoomImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.hotels.models.hotel_room_image_path, verbose_name='Фото номера')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='hotels.hotelroom', verbose_name='Номер отеля')),
            ],
            options={
                'verbose_name': 'Фото номера',
                'verbose_name_plural': 'Фото номера',
            },
        ),
        migrations.CreateModel(
            name='HotelRoomFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.CharField(max_length=255, verbose_name='Удобство')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_facilities', to='hotels.hotelroom', verbose_name='Номер отеля')),
            ],
            options={
                'verbose_name': 'Удобство номера',
                'verbose_name_plural': 'Удобства номера',
            },
        ),
    ]
