# Generated by Django 4.2.13 on 2024-08-08 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_eventbooking'),
        ('hotels', '0003_hotelroom_hotelroomimages_hotelroomfacilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_hotes', to='events.event', verbose_name='Тур'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='nights',
            field=models.IntegerField(default=0, verbose_name='Кол-во ночей'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='total_people',
            field=models.IntegerField(default=0, verbose_name='Кол-во человек'),
        ),
    ]
