# Generated by Django 4.2.13 on 2024-08-08 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotel_event_hotel_nights_hotel_total_people'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel', verbose_name='Отель'),
        ),
    ]
