# Generated by Django 4.2.13 on 2024-08-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_alter_hotelroom_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='address_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='address_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='address_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='country_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='country_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='country_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='full_description_en',
            field=models.TextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='full_description_ru',
            field=models.TextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='full_description_uz',
            field=models.TextField(null=True, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='name_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Название отеля'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='name_ru',
            field=models.CharField(max_length=500, null=True, verbose_name='Название отеля'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='name_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Название отеля'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='short_description_en',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='short_description_ru',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='short_description_uz',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='hotelentertainment',
            name='name_en',
            field=models.TextField(null=True, verbose_name='Развлечение'),
        ),
        migrations.AddField(
            model_name='hotelentertainment',
            name='name_ru',
            field=models.TextField(null=True, verbose_name='Развлечение'),
        ),
        migrations.AddField(
            model_name='hotelentertainment',
            name='name_uz',
            field=models.TextField(null=True, verbose_name='Развлечение'),
        ),
        migrations.AddField(
            model_name='hotelfacility',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Удобство'),
        ),
        migrations.AddField(
            model_name='hotelfacility',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Удобство'),
        ),
        migrations.AddField(
            model_name='hotelfacility',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Удобство'),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Удобства в номере'),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Удобства в номере'),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Удобства в номере'),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название номера'),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название номера'),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Название номера'),
        ),
        migrations.AddField(
            model_name='hotelroomfacilities',
            name='facility_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Удобство'),
        ),
        migrations.AddField(
            model_name='hotelroomfacilities',
            name='facility_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Удобство'),
        ),
        migrations.AddField(
            model_name='hotelroomfacilities',
            name='facility_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Удобство'),
        ),
    ]
