# Generated by Django 4.2.13 on 2024-08-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_hotel_address_en_hotel_address_ru_hotel_address_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_meals_included',
            field=models.BooleanField(default=True, verbose_name='Питание включено?'),
        ),
    ]
