# Generated by Django 4.2.13 on 2024-08-13 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_hotel_is_meals_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='allocation_type',
            field=models.CharField(choices=[('apart_hotel', 'Апарт-отель'), ('apartments', 'Апартаменты'), ('villa', 'Вилла'), ('cottage', 'Котедж'), ('hotel', 'Отель'), ('hostel', 'Хостел')], default='apart_hotel', max_length=50, verbose_name='Тип размещения'),
        ),
    ]
