# Generated by Django 4.2.13 on 2024-08-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_rename_rating_hotel_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='rating',
            field=models.CharField(choices=[('four_five', '4.5+'), ('four', '4+'), ('three', '3+')], default='four_five', max_length=15, verbose_name='Рейтинг'),
        ),
    ]
