# Generated by Django 4.2.13 on 2024-08-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_hotel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='food_type',
            field=models.CharField(blank=True, choices=[(None, ''), ('all_inclusive', 'Все включено'), ('without_food', 'Без питания'), ('lunch_dinner', 'Обед и ужин'), ('breakfast_lunch_dinner', 'Завтрак, обед или ужин')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Кол-во звёзд отеля'),
        ),
    ]
