# Generated by Django 4.2.13 on 2024-08-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_hotel_food_type_alter_hotel_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='facility',
            field=models.CharField(blank=True, choices=[(None, ''), ('bar', 'Бар'), ('air_conditioner', 'Кондиционер'), ('spa', 'Спа'), ('parking', 'Парковка')], max_length=50, null=True),
        ),
    ]
