# Generated by Django 4.2.13 on 2024-09-01 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_hotel_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='allocation_type',
            field=models.CharField(choices=[('apart_hotel', 'Апарт-отель'), ('apartments', 'Апартаменты'), ('villa', 'Вилла'), ('cottage', 'Котедж'), ('hotel', 'Отель'), ('hostel', 'Хостел')], max_length=50, null=True, verbose_name='Тип размещения'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='beach_line',
            field=models.CharField(choices=[('first', 'Первая'), ('second', 'Вторая'), ('third', 'Третья')], max_length=50, null=True, verbose_name='Линия пляжа'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='beach_type',
            field=models.CharField(choices=[('sand', 'Песок'), ('pebble', 'Галька'), ('platform', 'Платформа')], max_length=50, null=True, verbose_name='Тип пляжа'),
        ),
    ]
