# Generated by Django 4.2.13 on 2024-09-20 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0016_alter_hotel_allocation_type_alter_hotel_beach_line_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='distance_to_beach',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='price',
        ),
    ]
