# Generated by Django 4.2.13 on 2024-09-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0017_remove_hotel_distance_to_beach_remove_hotel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(null=True, verbose_name='Слаг'),
        ),
    ]
