# Generated by Django 4.2.13 on 2024-10-05 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_event_is_event_top'),
        ('hotels', '0018_hotel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_adult', models.PositiveIntegerField(default=0, verbose_name='Количество отдыхающих')),
                ('total_children', models.PositiveIntegerField(default=0, verbose_name='Количество детей')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_hotel', to='events.event', verbose_name='Тур')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_booking', to='hotels.hotel', verbose_name='Отель')),
                ('hotel_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_booking', to='hotels.hotelroom', verbose_name='Номер отеля')),
            ],
            options={
                'verbose_name': 'Бронь отеля',
                'verbose_name_plural': 'Брони отелей',
            },
        ),
    ]
