# Generated by Django 4.2.13 on 2024-11-09 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0020_delete_hotelbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='beach_line',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='beach_type',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='distance_to_airport',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='has_wifi',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='is_meals_included',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='short_description_en',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='short_description_ru',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='short_description_uz',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='slug',
        ),
    ]
