# Generated by Django 4.2.13 on 2024-11-12 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_event_corporate_client_price'),
        ('hotels', '0021_remove_hotel_beach_line_remove_hotel_beach_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelfacility',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='is_all_inclusive',
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='nights',
        ),
        migrations.RemoveField(
            model_name='hotelroom',
            name='until',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_hotels', to='events.event', verbose_name='Тур'),
        ),
        migrations.DeleteModel(
            name='HotelEntertainment',
        ),
        migrations.DeleteModel(
            name='HotelFacility',
        ),
    ]
