# Generated by Django 4.2.13 on 2025-01-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0022_remove_hotelfacility_hotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='averrage_price',
            field=models.FloatField(blank=True, help_text='Высчитывается средняя стоимость номер отеля', null=True, verbose_name='Средняя цена отеля'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='minimum_price',
            field=models.FloatField(blank=True, help_text='Высчитывается наименьшая стоимость номера данного отеля', null=True, verbose_name='Минимальная цена номера'),
        ),
    ]
