# Generated by Django 4.2.13 on 2025-01-17 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0023_hotel_averrage_price_hotel_minimum_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='event',
        ),
    ]
