# Generated by Django 4.2.13 on 2025-02-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0024_remove_hotel_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hote_type',
            field=models.CharField(choices=[(None, '-'), ('world', 'Мировой'), ('uzbekistan', 'По узбекистану')], default='uzbekistan', max_length=50, null=True),
        ),
    ]
