# Generated by Django 4.2.13 on 2025-02-02 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0025_hotel_hote_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hote_type',
            new_name='hotel_type',
        ),
    ]
