# Generated by Django 4.2.13 on 2025-02-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0027_hotelbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='is_all_inclusive',
            field=models.BooleanField(default=True, verbose_name='Все включено?'),
        ),
    ]
