# Generated by Django 4.2.13 on 2025-02-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0028_hotelroom_is_all_inclusive'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_all_inclusive',
            field=models.BooleanField(default=True, verbose_name='Все включено ?'),
        ),
    ]
