# Generated by Django 4.2.13 on 2025-02-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0030_hotel_price_for_child'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['name'], 'verbose_name': 'Отель', 'verbose_name_plural': 'Отели'},
        ),
    ]
