# Generated by Django 4.2.13 on 2025-03-05 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0032_hotel_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='averrage_price',
        ),
    ]
