# Generated by Django 4.2.13 on 2025-03-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0034_alter_hotel_is_all_inclusive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='price_for_not_resident_in_not_season',
            field=models.IntegerField(default=0, verbose_name='Цена для нерезидентов в не сезон'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price_for_not_resident_in_season',
            field=models.IntegerField(default=0, verbose_name='Цена для нерезидентов в сезон'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price_for_resident_in_not_season',
            field=models.IntegerField(default=0, verbose_name='цена для резидентов не в сезон'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price_for_resident_in_season',
            field=models.IntegerField(default=0, verbose_name='Цена для резидентов в сезон'),
        ),
    ]
