# Generated by Django 4.2.13 on 2025-03-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0035_hotel_price_for_not_resident_in_not_season_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='price_for_not_resident_in_not_season',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='price_for_not_resident_in_season',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='price_for_resident_in_not_season',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='price_for_resident_in_season',
        ),
    ]
