# Generated by Django 4.2.13 on 2025-03-13 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0036_remove_hotel_price_for_not_resident_in_not_season_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPriceInSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Начало сезона')),
                ('end', models.DateField(verbose_name='Конец сезона')),
                ('price_for_resident', models.IntegerField(verbose_name='Цена для резидента')),
                ('price_for_not_resident', models.IntegerField(verbose_name='Цена для нерезидента')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Цены в "сезон"',
                'verbose_name_plural': 'Цены в "сезон"',
            },
        ),
        migrations.CreateModel(
            name='HotelPriceInNotSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Начало не сезона')),
                ('end', models.DateField(verbose_name='Конец не сезона')),
                ('price_for_resident', models.IntegerField(verbose_name='Цена для резидента')),
                ('price_for_not_resident', models.IntegerField(verbose_name='Цена для нерезидента')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel', verbose_name='Отель')),
            ],
            options={
                'verbose_name': 'Цены в "не сезон"',
                'verbose_name_plural': 'Цены в "не сезон"',
            },
        ),
    ]
