# Generated by Django 4.2.13 on 2025-03-14 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0038_alter_hotelpriceinnotseason_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelpriceinnotseason',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_in_not_season', to='hotels.hotelroom', verbose_name='Отель'),
        ),
        migrations.AlterField(
            model_name='hotelpriceinseason',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_in_season', to='hotels.hotelroom', verbose_name='Отель'),
        ),
    ]
