# Generated by Django 4.2.13 on 2025-03-14 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0039_alter_hotelpriceinnotseason_hotel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelpriceinnotseason',
            old_name='hotel',
            new_name='hotel_room',
        ),
        migrations.RenameField(
            model_name='hotelpriceinseason',
            old_name='hotel',
            new_name='hotel_room',
        ),
    ]
