# Generated by Django 4.2.13 on 2025-04-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0040_rename_hotel_hotelpriceinnotseason_hotel_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='map_code',
            field=models.TextField(blank=True, null=True, verbose_name='Код для карты'),
        ),
    ]
