# Generated by Django 4.2.13 on 2024-07-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=10, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='user',
            name='surname',
            field=models.CharField(max_length=30, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
