# Generated by Django 4.2.13 on 2024-07-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100, verbose_name='Полное имя')),
                ('gender', models.CharField(max_length=100, verbose_name='Гендер')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('birth_certificate', models.FileField(upload_to='users/children/birth_certificates/', verbose_name='Свидетельство о рождении')),
            ],
            options={
                'verbose_name': 'Ребенок',
                'verbose_name_plural': 'Дети',
            },
        ),
        migrations.CreateModel(
            name='Tourist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('lastname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(max_length=20, verbose_name='Гендер')),
                ('passport_seria_and_number', models.CharField(max_length=20, verbose_name='Серия и номер паспорта')),
                ('expiration_date', models.DateField(verbose_name='Дата окончания паспорта')),
                ('citizen', models.CharField(max_length=100, verbose_name='Гражданство')),
            ],
            options={
                'verbose_name': 'Турист',
                'verbose_name_plural': 'Туристы',
            },
        ),
    ]
