# Generated by Django 4.2.13 on 2024-07-24 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_tourbooking_children_and_more'),
        ('users', '0005_children_tourist'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourist',
            name='tour_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourist_booking', to='events.tourbooking'),
        ),
    ]
