# Generated by Django 4.2.13 on 2024-08-02 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_children_user_tourist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='children',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='tourist',
            name='gender',
        ),
        migrations.AddField(
            model_name='children',
            name='gener',
            field=models.CharField(max_length=100, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='gener',
            field=models.CharField(max_length=100, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='children',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='children',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
