# Generated by Django 4.2.13 on 2024-08-02 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_children_gender_remove_tourist_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='children',
            name='gener',
        ),
        migrations.RemoveField(
            model_name='tourist',
            name='gener',
        ),
        migrations.AddField(
            model_name='children',
            name='gender',
            field=models.CharField(max_length=100, null=True, verbose_name='Гендер'),
        ),
        migrations.AddField(
            model_name='tourist',
            name='gender',
            field=models.CharField(max_length=20, null=True, verbose_name='Гендер'),
        ),
        migrations.AlterField(
            model_name='children',
            name='birth_certificate',
            field=models.FileField(null=True, upload_to='users/children/birth_certificates/', verbose_name='Свидетельство о рождении'),
        ),
        migrations.AlterField(
            model_name='children',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='citizen',
            field=models.CharField(max_length=100, null=True, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='expiration_date',
            field=models.DateField(null=True, verbose_name='Дата окончания паспорта'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='first_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='lastname',
            field=models.CharField(max_length=100, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='passport_seria_and_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Серия и номер паспорта'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tourist', to=settings.AUTH_USER_MODEL),
        ),
    ]
