# Generated by Django 4.2.13 on 2024-08-11 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_usertemp_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertemp',
            name='user',
        ),
    ]
