# Generated by Django 4.2.13 on 2024-08-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_usertemp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertemp',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='usertemp',
            name='verification_code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
