# Generated by Django 4.2.13 on 2024-08-13 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_usertemp_phone_number_usertemp_verification_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHotelSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_from', models.CharField(max_length=100, verbose_name='Откуда')),
                ('country_to', models.CharField(max_length=100, verbose_name='Куда')),
                ('departure_date', models.DateField(verbose_name='Дата вылета')),
                ('nights', models.PositiveSmallIntegerField(verbose_name='Кол-во ночей')),
                ('passengers', models.PositiveSmallIntegerField(verbose_name='Кол-во пассажиров')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotels_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История поиска тура',
                'verbose_name_plural': 'История поиска туров',
            },
        ),
    ]
