# Generated by Django 4.2.13 on 2024-09-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'Не выбрано'), ('male', 'Мужской'), ('female', 'Женский')], max_length=100, null=True, verbose_name='Гендер'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='issued_date',
            field=models.DateField(verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'Не выбрано'), ('male', 'Мужской'), ('female', 'Женский')], max_length=20, null=True, verbose_name='Гендер'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[(None, 'Не выбрано'), ('male', 'Мужской'), ('female', 'Женский')], max_length=10, null=True, verbose_name='Пол'),
        ),
    ]
