# Generated by Django 4.2.13 on 2024-11-06 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_children_gender_alter_passport_birth_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserHotelSearchHistory',
        ),
    ]
