# Generated by Django 4.2.13 on 2024-11-06 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_delete_userhotelsearchhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTemp',
        ),
    ]
