# Generated by Django 4.2.13 on 2024-11-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_delete_usertemp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[(None, 'Неизвестно'), ('guide', 'Гид'), ('transport_worker', 'Транспортник'), ('simple', 'Обычный пользователь')], default='simple', max_length=100, null=True, verbose_name='Тип пользователя'),
        ),
    ]
