# Generated by Django 4.2.13 on 2024-11-11 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0021_remove_hotel_beach_line_remove_hotel_beach_type_and_more'),
        ('users', '0024_usertourroute'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTourTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(blank=True, choices=[(None, ''), ('group', 'Групповой'), ('individual', 'Индивидуальный')], max_length=50, null=True, verbose_name='Тип транспорта')),
                ('transfer_type', models.CharField(max_length=150, verbose_name='Тип трансфера')),
                ('from_to', models.CharField(max_length=250, verbose_name='Откуда куда')),
                ('hotel_details', models.CharField(max_length=500, verbose_name='Данные гостиницы')),
                ('number_of_tourists', models.IntegerField(verbose_name='Количество туристов')),
                ('user_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transport', to='users.usertourroute')),
            ],
        ),
        migrations.CreateModel(
            name='UserTourHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tour_route', to='hotels.hotel')),
                ('user_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_route', to='users.usertourroute')),
            ],
        ),
    ]
