# Generated by Django 4.2.13 on 2024-11-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_usertourtransport_usertourhotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertourhotel',
            name='check_in_date',
            field=models.DateField(blank=True, null=True, verbose_name='Заезд'),
        ),
        migrations.AddField(
            model_name='usertourhotel',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Выезд'),
        ),
    ]
