# Generated by Django 4.2.13 on 2024-11-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_usertourhotel_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertourroute',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usertourtransport',
            name='user_route',
        ),
        migrations.DeleteModel(
            name='UserTourHotel',
        ),
        migrations.DeleteModel(
            name='UserTourRoute',
        ),
        migrations.DeleteModel(
            name='UserTourTransport',
        ),
    ]
