# Generated by Django 4.2.13 on 2025-01-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_usertourroute_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='birth_date',
            field=models.CharField(max_length=20, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='issued_date',
            field=models.CharField(max_length=20, verbose_name='Дата выдачи'),
        ),
    ]
