# Generated by Django 4.2.13 on 2025-01-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_alter_passport_birth_date_alter_passport_issued_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='birth_date',
            field=models.CharField(max_length=20, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='birth_date',
            field=models.CharField(max_length=20, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='expiration_date',
            field=models.CharField(max_length=20, null=True, verbose_name='Дата окончания паспорта'),
        ),
    ]
