# Generated by Django 4.2.13 on 2024-11-14 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0022_remove_hotelfacility_hotel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTourRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='UserTourTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_type', models.CharField(blank=True, choices=[(None, ''), ('group', 'Групповой'), ('individual', 'Индивидуальный')], max_length=50, null=True, verbose_name='Тип транспорта')),
                ('transfer_type', models.CharField(max_length=150, verbose_name='Тип трансфера')),
                ('from_to', models.CharField(max_length=250, verbose_name='Откуда куда')),
                ('hotel_details', models.CharField(max_length=500, verbose_name='Данные гостиницы')),
                ('number_of_tourists', models.IntegerField(verbose_name='Количество туристов')),
                ('user_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transport', to='user_route.usertourroute')),
            ],
        ),
        migrations.CreateModel(
            name='UserTourHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tour_route', to='hotels.hotel')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.hotelroom')),
                ('user_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_route', to='user_route.usertourroute')),
            ],
        ),
    ]
