# Generated by Django 4.2.13 on 2024-11-14 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0014_guide_price'),
        ('user_route', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRouteGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roles.guide')),
                ('user_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_guide', to='user_route.usertourroute')),
            ],
        ),
    ]
