# Generated by Django 4.2.13 on 2024-11-14 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_route', '0002_userrouteguide'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRouteAdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_video_shooting', models.BooleanField(default=False)),
                ('open_sim_card', models.BooleanField(default=False)),
                ('user_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_additional_service', to='user_route.usertourroute')),
            ],
        ),
    ]
