# Generated by Django 4.2.13 on 2024-11-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_route', '0003_userrouteadditionalservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertourroute',
            options={'verbose_name': 'Тур пользователя', 'verbose_name_plural': 'Туры пользователя'},
        ),
        migrations.AddField(
            model_name='usertourroute',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usertourroute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
