# Generated by Django 4.2.13 on 2024-12-22 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0015_guide_country'),
        ('user_route', '0004_alter_usertourroute_options_usertourroute_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrouteguide',
            name='date_from',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userrouteguide',
            name='date_to',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='userrouteguide',
            name='guide_route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='roles.guidetour'),
        ),
    ]
