# Generated by Django 4.2.13 on 2025-04-10 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_route', '0006_alter_userrouteadditionalservice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrouteadditionalservice',
            options={'verbose_name': 'Дополнительная услуга', 'verbose_name_plural': 'Дополнительные услуги'},
        ),
    ]
