# Generated by Django 4.2.13 on 2024-07-06 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Название статьи')),
                ('short_description', models.CharField(max_length=100, verbose_name='Краткое описание')),
                ('preview_img', models.ImageField(upload_to='images/articles/', verbose_name='Заставка')),
                ('published_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
