# Generated by Django 4.2.13 on 2024-07-22 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='full_description',
        ),
        migrations.CreateModel(
            name='ArticleTopParagraphs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Параграф')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_paragraphs', to='articles.article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleTextItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_items', to='articles.article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleImageItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/articles/', verbose_name='Фото')),
                ('descr', models.TextField(blank=True, null=True, verbose_name='Описание под фото')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_items', to='articles.article')),
            ],
        ),
    ]
