# Generated by Django 4.2.13 on 2024-07-22 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articledecoratedtextitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview_text',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='article',
            name='quote',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Цитата'),
        ),
    ]
