# Generated by Django 4.2.13 on 2024-08-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_preview_text_article_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview_text_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='article',
            name='preview_text_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='article',
            name='preview_text_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Слоган'),
        ),
        migrations.AddField(
            model_name='article',
            name='quote_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Цитата'),
        ),
        migrations.AddField(
            model_name='article',
            name='quote_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Цитата'),
        ),
        migrations.AddField(
            model_name='article',
            name='quote_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Цитата'),
        ),
        migrations.AddField(
            model_name='article',
            name='short_description_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='article',
            name='short_description_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='article',
            name='short_description_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Название статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Название статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_uz',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Название статьи'),
        ),
        migrations.AddField(
            model_name='articledecoratedtextitem',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='articledecoratedtextitem',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='articledecoratedtextitem',
            name='text_uz',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='articleimageitem',
            name='descr_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание под фото'),
        ),
        migrations.AddField(
            model_name='articleimageitem',
            name='descr_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание под фото'),
        ),
        migrations.AddField(
            model_name='articleimageitem',
            name='descr_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Описание под фото'),
        ),
        migrations.AddField(
            model_name='articletextitem',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='articletextitem',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='articletextitem',
            name='text_uz',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='articletopparagraphs',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Параграф'),
        ),
        migrations.AddField(
            model_name='articletopparagraphs',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Параграф'),
        ),
        migrations.AddField(
            model_name='articletopparagraphs',
            name='text_uz',
            field=models.TextField(null=True, verbose_name='Параграф'),
        ),
    ]
