# Generated by Django 4.2.13 on 2024-11-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_article_preview_text_en_article_preview_text_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='show_on_home_page',
            field=models.BooleanField(default=False, verbose_name='Показывать на главную стронице?'),
        ),
    ]
