# Generated by Django 4.2.13 on 2024-08-05 07:58

import apps.corporate_clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('about_company', models.TextField(blank=True, null=True, verbose_name='О компании')),
                ('client_type', models.CharField(choices=[(None, 'Не выбрано'), ('OWNER', 'Владелец компании'), ('HR', 'HR компании'), ('DIRECTOR', 'Директор компании')], max_length=10, verbose_name='Тип клиента')),
                ('khakimiyat_license', models.FileField(upload_to=apps.corporate_clients.models.license_upload_to, verbose_name='Лицензия из хакимиата')),
                ('uzb_tourism_license', models.FileField(upload_to=apps.corporate_clients.models.license_upload_to, verbose_name='Лицензия от коммитета туризма УЗБ')),
                ('lease_contract', models.FileField(upload_to=apps.corporate_clients.models.license_upload_to, verbose_name='Догор аренды')),
                ('director_passport', models.FileField(upload_to=apps.corporate_clients.models.license_upload_to, verbose_name='Паспорт директора')),
            ],
        ),
    ]
