# Generated by Django 4.2.13 on 2024-08-05 08:39

import apps.corporate_clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('about_company', models.TextField(blank=True, null=True, verbose_name='О компании')),
                ('client_type', models.CharField(choices=[(None, 'Не выбрано'), ('OWNER', 'Владелец компании'), ('HR', 'HR компании'), ('DIRECTOR', 'Директор компании')], max_length=10, verbose_name='Тип клиента')),
                ('khakimiyat_license', models.FileField(upload_to=apps.corporate_clients.models.license_upload_to, verbose_name='Лицензия из хакимиата')),
                ('uzb_tourism_license', models.FileField(upload_to=apps.corporate_clients.models.license_upload_to, verbose_name='Лицензия от коммитета туризма УЗБ')),
                ('lease_contract', models.FileField(upload_to=apps.corporate_clients.models.license_upload_to, verbose_name='Догор аренды')),
                ('director_passport', models.FileField(upload_to=apps.corporate_clients.models.license_upload_to, verbose_name='Паспорт директора')),
                ('charter', models.FileField(upload_to=apps.corporate_clients.models.license_upload_to, verbose_name='Устав')),
                ('address_and_index', models.CharField(max_length=150, verbose_name='Адрес и индекс')),
                ('fax', models.CharField(max_length=150, verbose_name='Факс')),
                ('corparate_account', models.CharField(max_length=150, verbose_name='К/счет')),
                ('mfo', models.CharField(max_length=150, verbose_name='МФО')),
                ('okonx', models.CharField(max_length=150, verbose_name='ОКОНХ')),
                ('okpo', models.CharField(max_length=150, verbose_name='ОКПО')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка корпоративного клиента',
                'verbose_name_plural': 'Заявки корпоративных клиентов',
            },
        ),
        migrations.DeleteModel(
            name='CorporateClient',
        ),
    ]
