# Generated by Django 4.2.13 on 2024-10-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_clients', '0002_corporateclientrequest_delete_corporateclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='our_clients/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Наши клиенты',
                'verbose_name_plural': 'Наши клиенты',
            },
        ),
    ]
