# Generated by Django 4.2.13 on 2024-10-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_clients', '0003_ourclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourclient',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='ourclient',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='ourclient',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Название'),
        ),
    ]
