# Generated by Django 4.2.13 on 2024-09-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_dailysales_serial_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['name'], 'verbose_name': 'Агент', 'verbose_name_plural': 'Агенты'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['name'], 'verbose_name': 'Поставщик', 'verbose_name_plural': 'Поставщики'},
        ),
        migrations.AlterField(
            model_name='dailysales',
            name='date',
            field=models.DateField(default='2024-09-17', verbose_name='Дата'),
        ),
    ]
