# Generated by Django 4.2.13 on 2024-09-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_agent_options_alter_supplier_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentreport',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='supplierreport',
            name='serial_number',
        ),
        migrations.AlterField(
            model_name='dailysales',
            name='date',
            field=models.DateField(default='2024-09-20', verbose_name='Дата'),
        ),
    ]
