# Generated by Django 4.2.13 on 2024-09-21 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_agentreport_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysales',
            name='date',
            field=models.DateField(default='2024-09-21', verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='DailySaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='2024-09-21', verbose_name='Дата')),
                ('passenger', models.CharField(max_length=100, verbose_name='Пассажир')),
                ('direction', models.CharField(max_length=100, verbose_name='Направление')),
                ('agent_sum', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Сумма агент')),
                ('supplier_sum', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Сумма поставщик')),
                ('margin', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Маржа')),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.agent', verbose_name='Агент')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Дневная продажа',
                'verbose_name_plural': 'Дневные продажи',
            },
        ),
    ]
