# Generated by Django 4.2.13 on 2024-09-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_dailysales_date_dailysaleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysaleitem',
            name='comment',
            field=models.TextField(default='', verbose_name='Комментарий'),
        ),
    ]
