# Generated by Django 4.2.13 on 2024-09-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_alter_dailysaleitem_date_alter_dailysales_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysaleitem',
            name='date',
            field=models.DateField(default='2024-09-29', verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='dailysales',
            name='date',
            field=models.DateField(default='2024-09-29', verbose_name='Дата'),
        ),
    ]
