# Generated by Django 4.2.13 on 2024-07-17 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя отправителя')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта отправителя')),
                ('text', models.TextField(verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Вопрос пользователя',
                'verbose_name_plural': 'Вопросы пользователя',
            },
        ),
    ]
