# Generated by Django 4.2.13 on 2024-09-11 19:40

import apps.main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_staticmediacontent_staticmediacontentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='is_answered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staticmediacontentitem',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=apps.main.models.static_media_content_file_path, verbose_name='Медиа контент для страницы'),
        ),
    ]
