# Generated by Django 4.2.13 on 2024-09-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_newsletter_is_answered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceWorkingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_uz', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=150, verbose_name='Подзаголовок')),
                ('subtitle_ru', models.CharField(max_length=150, null=True, verbose_name='Подзаголовок')),
                ('subtitle_uz', models.CharField(max_length=150, null=True, verbose_name='Подзаголовок')),
                ('subtitle_en', models.CharField(max_length=150, null=True, verbose_name='Подзаголовок')),
            ],
            options={
                'verbose_name': 'Работа сервиса',
                'verbose_name_plural': 'Работа сервиса',
            },
        ),
    ]
