# Generated by Django 4.2.13 on 2024-09-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tag_name_en_tag_name_ru_tag_name_uz'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticmediacontentitem',
            name='object_slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Название объекта для добавления фото'),
        ),
    ]
