# Generated by Django 4.2.13 on 2024-07-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('avatar', models.URLField(blank=True, null=True, verbose_name='Ссылка на фото')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('user_type', models.CharField(blank=True, choices=[(None, ''), ('simple', 'Физ лицо'), ('advanced', 'Юр лицо')], max_length=20, null=True, verbose_name='Тип пользователя')),
            ],
        ),
    ]
