# Generated by Django 4.2.13 on 2024-08-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('tour', 'Отзыв для тура'), ('hotel', 'Отзыв для отеля'), ('common', 'Обычный отзыв')], default='common', max_length=50, verbose_name='Тип отзыва'),
        ),
    ]
