# Generated by Django 4.2.13 on 2025-03-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_event_review_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/photos/', verbose_name='Фото'),
        ),
    ]
