# Generated by Django 4.2.13 on 2024-11-03 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_guidelanguage_guide_about_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidelanguage',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='roles.guide', verbose_name='Гид'),
        ),
    ]
