# Generated by Django 4.2.13 on 2024-11-03 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_alter_guide_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidelanguage',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='roles.guide', verbose_name='Гид'),
        ),
    ]
