# Generated by Django 4.2.13 on 2024-11-03 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_alter_guidelanguage_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название маршрута')),
                ('description', models.TextField(verbose_name='Описание программы')),
                ('additional', models.TextField(verbose_name='Дополнительно')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('gathering_place', models.TextField(verbose_name='Место встречи')),
                ('language', models.CharField(blank=True, choices=[('aa', 'Афарский язык'), ('ab', 'Абхазский язык'), ('ae', 'Авестийский язык'), ('af', 'Африкаанс'), ('ak', 'Акан'), ('am', 'Амхарский язык'), ('an', 'Арагонский язык'), ('ar', 'Арабский язык'), ('as', 'Ассамский язык'), ('av', 'Аварский язык'), ('ay', 'Аймара'), ('az', 'Азербайджанский язык'), ('ba', 'Башкирский язык'), ('be', 'Белорусский язык'), ('bg', 'Болгарский язык'), ('bh', 'Бихарский язык'), ('bi', 'Бислама'), ('bm', 'Бамбара'), ('bn', 'Бенгальский язык'), ('bo', 'Тибетский язык'), ('br', 'Бретонский язык'), ('bs', 'Боснийский язык'), ('ca', 'Каталонский язык'), ('ce', 'Чеченский язык'), ('ch', 'Чаморро'), ('co', 'Корсиканский язык'), ('cr', 'Язык кри'), ('cs', 'Чешский язык'), ('cu', 'Старославянский язык'), ('cv', 'Чувашский язык'), ('cy', 'Уэльсский язык'), ('da', 'Датский язык'), ('de', 'Немецкий язык'), ('dv', 'Мальдивский язык'), ('dz', 'Дзонг-кэ'), ('ee', 'Язык эве'), ('el', 'Греческий язык'), ('en', 'Английский язык'), ('eo', 'Эсперанто'), ('es', 'Испанский язык'), ('et', 'Эстонский язык'), ('eu', 'Баскский язык'), ('fa', 'Персидский язык'), ('ff', 'Фулах'), ('fi', 'Финский язык'), ('fj', 'Фиджи'), ('fo', 'Фарерский язык'), ('fr', 'Французский язык'), ('fy', 'Западно-фризский язык'), ('ga', 'Ирландский язык'), ('gd', 'Гэльский язык'), ('gl', 'Галисийскийязык'), ('gn', 'Язык гуарани'), ('gu', 'Гуджарати'), ('gv', 'Мэнский язык'), ('ha', 'Язык Хауса'), ('he', 'Иврит, древнееврейский язык'), ('hi', 'Хинди'), ('ho', 'Язык хиримоту'), ('hr', 'Хорватский язык'), ('ht', 'Гаитянский язык'), ('hu', 'Венгерский язык'), ('hy', 'Армянский язык'), ('hz', 'Гереро'), ('ia', 'Интерлингва'), ('in', 'Индонезийский язык'), ('ie', 'Интерлингве'), ('ig', 'Язык игбо'), ('ii', 'Язык ji провинции Сычуань'), ('ik', 'Инупиак'), ('io', 'Идо'), ('is', 'Исландский язык'), ('it', 'Итальянский язык'), ('iu', 'Инуитские языки'), ('ja', 'Японский язык'), ('jv', 'Яванский язык'), ('ka', 'Грузинский язык'), ('kg', 'Язык конго'), ('ki', 'Язык кикуйю'), ('kj', 'Киньяма'), ('kk', 'Казахский язык'), ('kl', 'Гренландский язык'), ('km', 'Кхмерский язык'), ('kn', 'Язык каннада'), ('ko', 'Корейский язык'), ('kr', 'Канури'), ('ks', 'Кашмири'), ('ku', 'Курдский язык'), ('kv', 'Язык коми'), ('kw', 'Корнский язык'), ('ky', 'Киргизский язык'), ('la', 'Латинский язык'), ('lb', 'Люксембургский язык'), ('lg', 'Ганда'), ('li', 'Лимбургский язык'), ('ln', 'Лингала'), ('lo', 'Лаосский язык'), ('lt', 'Литовский язык'), ('lu', 'Луба-катанга'), ('lv', 'Латышский язык'), ('mg', 'Малагасийский'), ('mh', 'Маршалльский'), ('mi', 'Маори'), ('mk', 'Македонский язык'), ('ml', 'Малаялам'), ('mn', 'Монгольский язык'), ('mo', 'Молдавский язык'), ('mr', 'Маратхи'), ('ms', 'Малайский язык'), ('mt', 'Мальтийский язык'), ('my', 'Бирманский язык'), ('na', 'Науруанский язык'), ('nb', 'Норвежский букмол'), ('nd', 'Ндебеле северный'), ('ne', 'Непальский язык'), ('ng', 'Ндунга'), ('nl', 'Голландский язык'), ('nn', 'Новонорвежский язык'), ('no', 'Норвежский язык'), ('nr', 'Ндебеле южный'), ('nv', 'Навахо'), ('ny', 'Ньянджа'), ('oc', 'Окситанский язык'), ('oj', 'Оджибве'), ('om', 'Оромо'), ('or', 'Ория'), ('os', 'Осетинский язык'), ('pa', 'Пенджабский'), ('pi', 'Пали'), ('pl', 'Польский язык'), ('ps', 'Пушту'), ('pt', 'Португальский язык'), ('qu', 'Кечуа'), ('rm', 'Ретороманский язык'), ('rn', 'Рунди'), ('ro', 'Румынский язык'), ('ru', 'Русский язык'), ('rw', 'Руанда'), ('sa', 'Санскрит'), ('sc', 'Сардинский язык'), ('sd', 'Синдхи'), ('se', 'Северосаамский язык'), ('sg', 'Санго'), ('si', 'Сингальский'), ('sk', 'Словакский язык'), ('sl', 'Словенский язык'), ('sm', 'Самоанский язык'), ('sn', 'Шона'), ('so', 'Сомали'), ('sq', 'Албанский язык'), ('sr', 'Сербский язык'), ('ss', 'Свази'), ('st', 'Сото южный'), ('su', 'Сунданский язык'), ('sv', 'Шведский язык'), ('sw', 'Суахили'), ('ta', 'Тамильский'), ('te', 'Телугу'), ('tg', 'Таджикский язык'), ('th', 'Тайский язык'), ('ti', 'Тигре'), ('tk', 'Туркменский язык'), ('tl', 'Тагальский язык'), ('tn', 'Язык Тсвана'), ('to', 'Тонганский язык'), ('tr', 'Турецкий язык'), ('ts', 'Язык тсонга'), ('tt', 'Татарский язык'), ('tw', 'Язык тви'), ('ty', 'Таитянский язык'), ('ug', 'Уйгурский язык'), ('uk', 'Украинский язык'), ('ur', 'Урду'), ('uz', 'Узбекский язык'), ('ve', 'Венда'), ('vi', 'Вьетнамский язык'), ('vo', 'Волапюк'), ('wo', 'Волоф'), ('xh', 'Язык коса'), ('yi', 'Идиш'), ('yo', 'Йоруба'), ('za', 'Чжуанский язык'), ('zh', 'Китайский язык'), ('zu', 'Язык зулу')], max_length=50, null=True, verbose_name='Язык')),
                ('tour_duration', models.CharField(blank=True, choices=[(None, ''), ('half_our', 'Пол часа'), ('hour', 'Час'), ('one_and_half_our', '1,5 часа')], max_length=100, null=True, verbose_name='Длительность проведения')),
                ('number_of_people', models.CharField(blank=True, choices=[(None, ''), ('with_children', 'Можно с детьми'), ('pay_for_children', 'Доплата за ребенка')], max_length=100, null=True, verbose_name='Количество участников')),
                ('mode_of_transportation', models.CharField(blank=True, choices=[(None, ''), ('on_foot', 'Пешком'), ('by_car', 'На авто'), ('indoors', 'В помещении'), ('by_bike', 'На велосипеде'), ('by_bus', 'На автобусе'), ('on_a_motorcycle', 'На мотоцикле'), ('on_the_ship', 'На корабле'), ('other', 'Другое (впишу сам)')], max_length=100, null=True, verbose_name='Способ передвижения')),
                ('working_with_orders', models.CharField(blank=True, choices=[(None, ''), ('half_our', 'За пол часа'), ('hour', 'За час'), ('any_time', 'Можно бронировать в любой момент')], max_length=100, null=True, verbose_name='Работа с заказами')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.guide', verbose_name='Гид')),
            ],
            options={
                'verbose_name': 'Маршрут гида',
                'verbose_name_plural': 'Маршруты гидов',
            },
        ),
        migrations.CreateModel(
            name='GuideTourPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='guides/routes/tours/', verbose_name='Фото тура')),
                ('guide_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.guidetour', verbose_name='Маршрут тура')),
            ],
        ),
        migrations.CreateModel(
            name='GuideTourOrganizationalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('guide_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.guidetour', verbose_name='Маршрут гида')),
            ],
        ),
        migrations.CreateModel(
            name='GuideTourExpectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Ожидание туриста')),
                ('guide_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.guidetour', verbose_name='Маршрут')),
            ],
        ),
        migrations.CreateModel(
            name='GuideSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('guide_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roles.guidetour', verbose_name='Маршрут тура')),
            ],
            options={
                'verbose_name': 'Расписание гида',
                'verbose_name_plural': 'Расписания гидов',
            },
        ),
    ]
