# Generated by Django 4.2.13 on 2024-11-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0006_guidetour_guidetourphoto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='guides/avatars/', verbose_name='Фото гида'),
        ),
    ]
