# Generated by Django 4.2.13 on 2024-11-04 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0008_alter_guideschedule_guide_tour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidepassport',
            name='guide',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='passports', to='roles.guide', verbose_name='Гид'),
        ),
    ]
