# Generated by Django 4.2.13 on 2024-11-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0009_alter_guidepassport_guide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidepassport',
            name='agree_to_save_data',
            field=models.BooleanField(blank=True, null=True, verbose_name='Согласен на сохранение паспортных данных'),
        ),
        migrations.AlterField(
            model_name='guidepassport',
            name='citizen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='guidepassport',
            name='issued_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Кем выдан'),
        ),
        migrations.AlterField(
            model_name='guidepassport',
            name='issued_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='guidepassport',
            name='ready_for_trip',
            field=models.BooleanField(blank=True, null=True, verbose_name='Готов к международным поездкам'),
        ),
        migrations.AlterField(
            model_name='guidepassport',
            name='seria_and_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Серия и номер'),
        ),
    ]
