# Generated by Django 4.2.13 on 2024-11-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0011_guide_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidetour',
            name='language',
            field=models.CharField(blank=True, choices=[], max_length=50, null=True, verbose_name='Язык'),
        ),
    ]
