# Generated by Django 4.2.13 on 2024-11-10 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0012_alter_guidetour_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guidetour',
            old_name='mode_of_transportation',
            new_name='transportation_type',
        ),
        migrations.RemoveField(
            model_name='guidetour',
            name='number_of_people',
        ),
        migrations.RemoveField(
            model_name='guidetour',
            name='tour_duration',
        ),
        migrations.AddField(
            model_name='guidetour',
            name='duration',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Длительность маршрута'),
        ),
        migrations.AddField(
            model_name='guidetour',
            name='participants_number',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Количество участников'),
        ),
        migrations.AlterField(
            model_name='guidetour',
            name='additional',
            field=models.TextField(blank=True, null=True, verbose_name='Дополнительно'),
        ),
        migrations.AlterField(
            model_name='guidetour',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='guidetour',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='guidetour',
            name='gathering_place',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Место встречи'),
        ),
        migrations.AlterField(
            model_name='guidetour',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='roles.guide', verbose_name='Гид'),
        ),
        migrations.AlterField(
            model_name='guidetour',
            name='language',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='guidetour',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='guidetour',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название маршрута'),
        ),
        migrations.AlterField(
            model_name='guidetour',
            name='working_with_orders',
            field=models.CharField(blank=True, choices=[(None, ''), ('half_our', 'За пол часа'), ('hour', 'За час'), ('any_time', 'Можно бронировать в любой момент')], max_length=50, null=True, verbose_name='Работа с заказами'),
        ),
    ]
