# Generated by Django 4.2.13 on 2024-11-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0013_rename_mode_of_transportation_guidetour_transportation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена за тур'),
        ),
    ]
