# Generated by Django 4.2.13 on 2024-12-09 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0014_guide_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна'),
        ),
    ]
